
services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here
      MYSQL_DATABASE: university
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_pass
    volumes:
      - db_data:/var/lib/mysql
    # map to a different host port if your host already has mysql
    ports:
      - "3307:3306"

  backend:
    build:
      context: ./university
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # override Spring properties with env vars
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/university?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: demo_user
      SPRING_DATASOURCE_PASSWORD: demo_pass
      # useful for logs
      SPRING_PROFILES_ACTIVE: prod

  # for production 
  # frontend:
  #   build:
  #     context: ./frontend
  #   volumes:
  #     - ./frontend:/app # LOCAL CODE â†’ CONTAINER (Hot reload!)
  #     - /app/node_modules
  #   command: npm run dev
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NEXT_PUBLIC_API_URL: http://backend:8080
  #   depends_on:
  #     - backend

  # for development 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    depends_on:
      - backend
    develop:
      watch:
        # Rebuild if dependencies change
        - action: sync+restart
          path: ./frontend/package.json
          target: /app/package.json
        # Sync source files for hot reload (Node.js/Next.js)
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
            - .git/




volumes:
  db_data:
